
### GET - Obtenir tots els TODOs
GET http://localhost:3000/todos

### GET - Obtenir un TODO per id
GET http://localhost:3000/todos/2


### GET - Obtenir un TODO per prioritat
GET http://localhost:3000/todos/prioritat/alta


### POST - Crear un nou TODO - correcte
POST http://localhost:3000/todos
Content-Type: application/json

{
  "titol": "Nou TODO Token",
  "descripcio": "Això és un nou TODO creat per POST",
  "completat": 0,
  "prioritat": "alta"
}

### POST - Crear un nou TODO - error TÍTOL
POST http://localhost:3000/todos
Content-Type: application/json

{
  "descripcio": "Això és un nou TODO creat per POST",
  "completat": 0,
  "prioritat": "alta"
}


### POST - Crear un nou TODO - sense camps opcionals
POST http://localhost:3000/todos
Content-Type: application/json

{
  "titol": "Nou TODO II"
}

### PUT - Actualitzar TODO - completa
PUT http://localhost:3000/todos/2
Content-Type: application/json

{
  "titol": "TODO actualitzat",
  "descripcio": "Modificació amb PUT",
  "completat": 1,
  "prioritat": "mitjana"
}

### PUT - Actualitzar TODO - alguns camps
PUT http://localhost:3000/todos/2
Content-Type: application/json

{
  "titol": "TODO actualitzat II",
  "descripcio": "Modificació amb PUT :)",
  "completat": 1,
  "prioritat": "mitjana"
}


### PUT - Actualitzar TODO - error (falten camps)
PUT http://localhost:3000/todos/2
Content-Type: application/json

{
  "titol": "TODO actualitzat II",
  "descripcio": "Modificació amb PUT :)"
}

### PUT - Actualitzar TODO - error (id inexistent)
PUT http://localhost:3000/todos/23
Content-Type: application/json

{
  "titol": "TODO actualitzat II",
  "descripcio": "Modificació amb PUT :)",
  "completat": 1,
  "prioritat": "mitjana"
}



### DELETE - Eliminar TODO - correcte
DELETE http://localhost:3000/todos/2


### DELETE - Eliminar TODO - error (falta id)
DELETE http://localhost:3000/todos/23


