### GET - Tots els usuaris
GET http://localhost:3000/usuaris
Content-Type: application/json


### POST - Registrar usuari: solveTheX
POST http://localhost:3000/usuaris
Content-Type: application/json

{
  "username": "solveTheX",
  "password": "reto"
}

### POST - Registrar usuari: prova
POST http://localhost:3000/usuaris
Content-Type: application/json

{
  "username": "test",
  "password": "1234"
}

### POST - Registrar usuari - error: usuari ja existent
POST http://localhost:3000/usuaris
Content-Type: application/json

{
  "username": "irie1234",
  "password": "contra1234"
}


### POST - Login d'usuari: correcte
POST http://localhost:3000/usuaris/login
Content-Type: application/json

{
  "username": "solveTheX",
  "password": "reto"
}

### POST - Login: usuari inexistent
POST http://localhost:3000/usuaris/login
Content-Type: application/json

{
  "username": "irie12",
  "password": "contra1234"
}

### POST - Login: contrasenya incorrecte
POST http://localhost:3000/usuaris/login
Content-Type: application/json

{
  "username": "irie1234",
  "password": "patata"
}
